"use client";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const choices = [["all", "Tutte le anomalie"], ["overlap", "Sovrapposizioni"], ["duration_short", "Durata < 5 min"], ["duration_long", "Durata > 12 h"], ["temporal_inconsistency", "Incoerenza temporale"], ["missing_project", "Progetto mancante"], ["missing_task", "Task mancante"], ["active_lock_missing", "Blocco mancante"]] as const;
export default function ClockifyAuditClient(): JSX.Element {
  const [anomaly, setAnomaly] = useState("all"); const [data, setData] = useState<any>({ entries: [] }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const load = useCallback(async (cursor?: string) => { setLoading(true); try { const query = new URLSearchParams({ ...(anomaly === "all" ? {} : { anomaly }), ...(cursor ? { cursor } : {}) }); const response = await fetch(`/api/clockify/v2/audit?${query}`, { cache: "no-store" }); const value = await response.json(); if (!response.ok) throw new Error(value.error || "Impossibile caricare l'audit"); setData((old: any) => cursor ? { ...value, entries: [...old.entries, ...value.entries] } : value); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Errore di caricamento"); } finally { setLoading(false); } }, [anomaly]);
  useEffect(() => { void load(); }, [load]);
  return <main className="min-h-screen bg-secondary"><div className="mx-auto max-w-6xl space-y-5 px-4 py-6"><div><h1 className="text-2xl font-bold">Audit rendicontazione</h1><p className="text-sm text-muted-foreground">Sola lettura: anomalie e contesto necessario per correggerle.</p></div><div className="flex gap-2"><Select value={anomaly} onValueChange={setAnomaly}><SelectTrigger className="w-64"><SelectValue /></SelectTrigger><SelectContent>{choices.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={loading} onClick={() => void load()}>{loading ? "Caricamento…" : "Aggiorna"}</Button></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="overflow-x-auto rounded border bg-card"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Data</th><th>Utente</th><th>Progetto</th><th>Durata</th><th>Motivi</th></tr></thead><tbody>{data.entries.map((entry: any) => <tr className="border-b" key={entry.id}><td className="p-3">{String(entry.workDate).slice(0, 10)}</td><td>{entry.user?.name || entry.user?.email}</td><td>{entry.project ? `${entry.project.client} / ${entry.project.name}` : "—"}</td><td>{entry.durationMin} min</td><td>{entry.reasons.join(", ")}</td></tr>)}</tbody></table></div>{data.nextCursor && <Button variant="outline" disabled={loading} onClick={() => void load(data.nextCursor)}>Carica altro</Button>}</div></main>;
}
