"use client";

import { useMemo } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ClockifyV2Entry } from "./clockify-v2-types";

type View = "day" | "week" | "month";
function romeDate(value: Date): string { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Rome", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(value); const p = (key: string) => parts.find((part) => part.type === key)?.value || ""; return `${p("year")}-${p("month")}-${p("day")}`; }
function addDays(value: Date, days: number): Date { const copy = new Date(value); copy.setUTCDate(copy.getUTCDate() + days); return copy; }
export type ClockifyCalendarView = View;
export function getClockifyCalendarRange(view: View, anchor: Date): { from: string; to: string } { const local = romeDate(anchor); const date = new Date(`${local}T12:00:00Z`); if (view === "day") return { from: local, to: local }; if (view === "month") { const from = `${local.slice(0, 7)}-01`; const end = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0)); return { from, to: end.toISOString().slice(0, 10) }; } const monday = addDays(date, -((date.getUTCDay() + 6) % 7)); return { from: monday.toISOString().slice(0, 10), to: addDays(monday, 6).toISOString().slice(0, 10) }; }
export function stepClockifyCalendarAnchor(view: View, anchor: Date, direction: -1 | 1): Date { if (view !== "month") return addDays(anchor, direction * (view === "week" ? 7 : 1)); const local = romeDate(anchor); const date = new Date(`${local}T12:00:00Z`); return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + direction, 1, 12)); }

export function ClockifyV2Calendar({ entries, onView, view, anchor, onViewChange, onAnchorChange }: { entries: ClockifyV2Entry[]; onView: (entry: ClockifyV2Entry) => void; view: View; anchor: Date; onViewChange: (view: View) => void; onAnchorChange: (anchor: Date) => void }): JSX.Element {
  const dates = useMemo(() => { const range = getClockifyCalendarRange(view, anchor); const start = new Date(`${range.from}T12:00:00Z`); const end = new Date(`${range.to}T12:00:00Z`); return Array.from({ length: Math.round((end.getTime() - start.getTime()) / 86_400_000) + 1 }, (_, index) => romeDate(addDays(start, index))); }, [anchor, view]);
  const byDate = useMemo(() => new Map(dates.map((date) => [date, entries.filter((entry) => romeDate(new Date(entry.workDate)) === date)])), [dates, entries]);
  return <section className="rounded-lg border bg-card p-4" aria-label="Calendario rendicontazione"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1" role="group" aria-label="Vista calendario">{(["day", "week", "month"] as View[]).map((item) => <Button key={item} size="sm" variant={view === item ? "default" : "outline"} onClick={() => onViewChange(item)}>{item === "day" ? "Giorno" : item === "week" ? "Settimana" : "Mese"}</Button>)}</div><div className="flex items-center gap-1"><Button size="icon" variant="outline" aria-label="Periodo precedente" onClick={() => onAnchorChange(stepClockifyCalendarAnchor(view, anchor, -1))}><ChevronLeft className="h-4 w-4" /></Button><span className="min-w-28 text-center text-sm font-medium">{dates[0]}{dates.length > 1 ? ` – ${dates[dates.length - 1]}` : ""}</span><Button size="icon" variant="outline" aria-label="Periodo successivo" onClick={() => onAnchorChange(stepClockifyCalendarAnchor(view, anchor, 1))}><ChevronRight className="h-4 w-4" /></Button></div></div><div className={view === "month" ? "grid gap-2 sm:grid-cols-4 lg:grid-cols-7" : "grid gap-2 sm:grid-cols-2 lg:grid-cols-7"}>{dates.map((date) => <div key={date} className="min-h-20 rounded border p-2"><div className="mb-1 text-xs font-medium">{date}</div>{(byDate.get(date) || []).map((entry) => <button key={entry.id} type="button" className="mb-1 block w-full truncate rounded bg-secondary px-2 py-1 text-left text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => onView(entry)} aria-label={`Apri ${entry.description}`}>{entry.description}</button>)}</div>)}</div></section>;
}
