"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Clock3 } from "lucide-react";
import { useSession } from "next-auth/react";
import { toast } from "react-hot-toast";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ClockifyV2EntryForm } from "./clockify-v2-entry-form";
import { ClockifyV2EntryList } from "./clockify-v2-entry-list";
import { ClockifyV2Calendar, getClockifyCalendarRange, type ClockifyCalendarView } from "./clockify-v2-calendar";
import type { ClockifyV2Entry, ClockifyV2Form, ClockifyV2Project, ClockifyV2Warning } from "./clockify-v2-types";

function romeDate(value: Date): string {
  const parts = new Intl.DateTimeFormat("en", { timeZone: "Europe/Rome", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(value);
  const part = (type: string) => parts.find((item) => item.type === type)?.value || "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}
const today = (): string => romeDate(new Date());
const initialForm = (): ClockifyV2Form => ({ projectId: "", taskId: "", description: "", tags: "", billable: false, date: today(), startTime: "09:00", endAt: "10:00", durationMin: "60", mode: "end" });
const dateForEntry = (entry: ClockifyV2Entry): string => romeDate(new Date(entry.workDate));
const timeForEntry = (value: string): string => new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Rome", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value));

async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error || "Operazione non riuscita"); return data as T; }

export default function ClockifyV2ClientPage(): JSX.Element {
  const { data: session } = useSession();
  const meId = String((session?.user as { id?: string } | undefined)?.id || "");
  const [projects, setProjects] = useState<ClockifyV2Project[]>([]); const [entries, setEntries] = useState<ClockifyV2Entry[]>([]);
  const [days, setDays] = useState<Array<{ date: string; entries: ClockifyV2Entry[]; totalMin: number; billableMin: number }>>([]); const [weeks, setWeeks] = useState<Array<{ startDate: string; totalMin: number; billableMin: number }>>([]); const [periodTotal, setPeriodTotal] = useState({ totalMin: 0, billableMin: 0 }); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loadingMore, setLoadingMore] = useState(false); const [calendarView, setCalendarView] = useState<ClockifyCalendarView>("week"); const [calendarAnchor, setCalendarAnchor] = useState(() => new Date());
  const [form, setForm] = useState<ClockifyV2Form>(initialForm); const [editing, setEditing] = useState<ClockifyV2Entry | null>(null); const [warnings, setWarnings] = useState<ClockifyV2Warning[]>([]); const [saving, setSaving] = useState(false); const [detailEntry, setDetailEntry] = useState<ClockifyV2Entry | null>(null); const [splitEntry, setSplitEntry] = useState<ClockifyV2Entry | null>(null); const [splitDate, setSplitDate] = useState(""); const [splitTime, setSplitTime] = useState("");
  const range = useMemo(() => getClockifyCalendarRange(calendarView, calendarAnchor), [calendarAnchor, calendarView]);
  const load = useCallback(async (cursor?: string) => { try { const [catalog, report] = await Promise.all([cursor ? Promise.resolve(null) : request<{ projects: ClockifyV2Project[] }>("/api/clockify/v2/entries/catalog"), request<{ entries: ClockifyV2Entry[]; groups: { days: typeof days; weeks: typeof weeks; period: typeof periodTotal }; nextCursor: string | null }>(`/api/clockify/v2/entries?from=${range.from}&to=${range.to}&limit=100${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)]); if (catalog) setProjects(catalog.projects); setEntries((current) => cursor ? [...current, ...report.entries] : report.entries); setDays((current) => cursor ? mergeDays(current, report.groups.days) : report.groups.days); setWeeks((current) => cursor ? mergeWeeks(current, report.groups.weeks) : report.groups.weeks); setPeriodTotal(report.groups.period); setNextCursor(report.nextCursor); } catch (error) { toast.error(error instanceof Error ? error.message : "Errore di caricamento"); } }, [range]);
  useEffect(() => { void load(); }, [load]);
  const tags = useMemo(() => [...new Set(entries.flatMap((entry) => entry.tags || []))].sort(), [entries]);
  async function save(): Promise<void> { setSaving(true); setWarnings([]); try { const payload = { projectId: form.projectId, taskId: form.taskId || null, description: form.description, tags: form.tags.split(",").map((tag) => tag.trim()).filter(Boolean), billable: form.billable, date: form.date, startTime: form.startTime, ...(form.mode === "end" ? { endAt: form.endAt } : { durationMin: Number(form.durationMin) }) }; const result = await request<{ warnings: ClockifyV2Warning[] }>(editing ? `/api/clockify/v2/entries/${editing.id}` : "/api/clockify/v2/entries", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setWarnings(result.warnings || []); toast.success(editing ? "Attività aggiornata" : "Attività creata"); setEditing(null); setForm(initialForm()); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Salvataggio non riuscito"); } finally { setSaving(false); } }
  function edit(entry: ClockifyV2Entry): void { setDetailEntry(null); setEditing(entry); setWarnings([]); setForm({ projectId: entry.projectId, taskId: entry.taskId || "", description: entry.description, tags: (entry.tags || []).join(", "), billable: entry.billable, date: dateForEntry(entry), startTime: timeForEntry(entry.startAt), endAt: timeForEntry(entry.endAt), durationMin: String(entry.durationMin), mode: "end" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function duplicate(entry: ClockifyV2Entry): void { edit(entry); setEditing(null); setDetailEntry(null); toast("Modifica data o orario e salva per creare una copia."); }
  function openSplit(entry: ClockifyV2Entry): void { setDetailEntry(null); setSplitEntry(entry); setSplitDate(dateForEntry(entry)); setSplitTime(timeForEntry(entry.startAt)); }
  async function remove(entry: ClockifyV2Entry): Promise<void> { if (!window.confirm("Eliminare questa attività?")) return; try { await request(`/api/clockify/v2/entries/${entry.id}`, { method: "DELETE" }); setDetailEntry(null); toast.success("Attività eliminata"); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Eliminazione non riuscita"); } }
  async function split(): Promise<void> { if (!splitEntry || !splitDate || !splitTime) return; try { await request(`/api/clockify/v2/entries/${splitEntry.id}/split`, { method: "POST", body: JSON.stringify({ splitDate, splitTime }) }); setSplitEntry(null); toast.success("Attività divisa"); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Divisione non riuscita"); } }
  async function loadMore(): Promise<void> { if (!nextCursor) return; setLoadingMore(true); try { await load(nextCursor); } finally { setLoadingMore(false); } }
  async function changeLock(entry: ClockifyV2Entry, locked: boolean): Promise<void> { try { await request(`/api/clockify/v2/entries/${entry.id}/lock`, { method: locked ? "POST" : "DELETE" }); toast.success(locked ? "Attività bloccata" : "Attività sbloccata"); setDetailEntry(null); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Operazione non riuscita"); } }
  const isAdmin = (session?.user as { globalRole?: string } | undefined)?.globalRole === "admin";
  const detailEditable = !!detailEntry && detailEntry.userId === meId && !detailEntry.effectiveLocked;
  return <main className="min-h-screen bg-secondary"><div className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6 sm:py-8"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Clock3 className="h-6 w-6" />Rendicontazione</h1><p className="text-sm text-muted-foreground">Inserimento manuale delle attività · orari interpretati in Europa/Roma.</p></div><ClockifyV2EntryForm form={form} projects={projects} tagSuggestions={tags} saving={saving} warnings={warnings} onChange={setForm} onSubmit={save} editing={editing} onCancelEdit={() => { setEditing(null); setForm(initialForm()); setWarnings([]); }} /><ClockifyV2Calendar entries={entries} onView={setDetailEntry} view={calendarView} anchor={calendarAnchor} onViewChange={setCalendarView} onAnchorChange={setCalendarAnchor} /><ClockifyV2EntryList days={days} weeks={weeks} period={periodTotal} onView={setDetailEntry} />{nextCursor && <div className="flex justify-center"><Button variant="outline" disabled={loadingMore} onClick={() => void loadMore()}>{loadingMore ? "Caricamento…" : "Carica altre attività"}</Button></div>}
    <Dialog open={!!detailEntry} onOpenChange={(open) => !open && setDetailEntry(null)}><DialogContent><DialogHeader><DialogTitle>Dettaglio attività</DialogTitle></DialogHeader>{detailEntry && <div className="space-y-3 text-sm"><div><span className="font-medium">Progetto:</span> {detailEntry.project?.client ? `${detailEntry.project.client} / ` : ""}{detailEntry.project?.name || "Progetto archiviato"}</div><div><span className="font-medium">Quando:</span> {dateForEntry(detailEntry)} {timeForEntry(detailEntry.startAt)}–{timeForEntry(detailEntry.endAt)} (Europa/Roma)</div><div><span className="font-medium">Descrizione:</span> {detailEntry.description}</div><div><span className="font-medium">Attività:</span> {detailEntry.task || "—"}</div><div><span className="font-medium">Tag:</span> {detailEntry.tags.join(", ") || "—"}</div>{detailEntry.effectiveLocked && <p className="rounded-md border border-warning bg-warning/10 p-2">Questa attività è bloccata e non può essere modificata.</p>}<DialogFooter>{detailEditable && <><Button variant="outline" onClick={() => edit(detailEntry)}>Modifica</Button><Button variant="outline" onClick={() => duplicate(detailEntry)}>Duplica</Button><Button variant="outline" onClick={() => openSplit(detailEntry)}>Dividi</Button><Button variant="destructive" onClick={() => void remove(detailEntry)}>Elimina</Button></>}{isAdmin && <Button variant="outline" onClick={() => void changeLock(detailEntry, !detailEntry.effectiveLocked)}>{detailEntry.effectiveLocked ? "Sblocca manualmente" : "Blocca manualmente"}</Button>}<Button variant="outline" onClick={() => setDetailEntry(null)}>Chiudi</Button></DialogFooter></div>}</DialogContent></Dialog>
    <Dialog open={!!splitEntry} onOpenChange={(open) => !open && setSplitEntry(null)}><DialogContent><DialogHeader><DialogTitle>Dividi attività</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="split-date">Data (Europa/Roma)</Label><Input id="split-date" type="date" value={splitDate} onChange={(event) => setSplitDate(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="split-time">Ora (Europa/Roma)</Label><Input id="split-time" type="time" value={splitTime} onChange={(event) => setSplitTime(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setSplitEntry(null)}>Annulla</Button><Button onClick={() => void split()} disabled={!splitDate || !splitTime}>Dividi</Button></DialogFooter></DialogContent></Dialog></div></main>;
}

function mergeDays(current: Array<{ date: string; entries: ClockifyV2Entry[]; totalMin: number; billableMin: number }>, incoming: Array<{ date: string; entries: ClockifyV2Entry[]; totalMin: number; billableMin: number }>) { const map = new Map(current.map((day) => [day.date, { ...day, entries: [...day.entries] }])); for (const day of incoming) { const previous = map.get(day.date); map.set(day.date, previous ? { ...previous, entries: [...previous.entries, ...day.entries], totalMin: previous.totalMin + day.totalMin, billableMin: previous.billableMin + day.billableMin } : day); } return [...map.values()].sort((a, b) => a.date.localeCompare(b.date)); }
function mergeWeeks(current: Array<{ startDate: string; totalMin: number; billableMin: number }>, incoming: Array<{ startDate: string; totalMin: number; billableMin: number }>) { const map = new Map(current.map((week) => [week.startDate, { ...week }])); for (const week of incoming) { const previous = map.get(week.startDate); map.set(week.startDate, previous ? { ...previous, totalMin: previous.totalMin + week.totalMin, billableMin: previous.billableMin + week.billableMin } : week); } return [...map.values()].sort((a, b) => a.startDate.localeCompare(b.startDate)); }
