"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, ExternalLink, Printer, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type ReportType = "summary" | "detailed" | "weekly";
type Filters = Record<string, string>;
const today = new Date().toISOString().slice(0, 10);
const firstDay = `${today.slice(0, 7)}-01`;
const initialFilters: Filters = { from: firstDay, to: today, department: "", userId: "", client: "", projectId: "", taskId: "", tag: "", locked: "", description: "", billable: "" };
function query(filters: Filters, type: ReportType, groupBy: string, increment: string, mode: string): string { const value = new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== "")), reportType: type, ...(groupBy ? { groupBy } : {}), ...(increment ? { roundingIncrement: increment, roundingMode: mode } : {}) }); return value.toString(); }
function minutes(value: number): string { return `${Math.floor(value / 60)}h ${String(value % 60).padStart(2, "0")}m`; }

export default function ClockifyReportsClient(): JSX.Element {
  const [tab, setTab] = useState<ReportType | "shared">("summary"); const [filters, setFilters] = useState<Filters>(initialFilters); const [groupBy, setGroupBy] = useState("project"); const [increment, setIncrement] = useState(""); const [mode, setMode] = useState("nearest"); const [report, setReport] = useState<any>(null); const [shares, setShares] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [shareUrl, setShareUrl] = useState("");
  const reportType = tab === "shared" ? "summary" : tab;
  const params = useMemo(() => query(filters, reportType, groupBy, increment, mode), [filters, reportType, groupBy, increment, mode]);
  const load = useCallback(async () => { if (tab === "shared") { const response = await fetch("/api/clockify/v2/reports/shares", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Impossibile caricare le condivisioni"); setShares(data.shares || []); return; } setLoading(true); setError(""); try { const response = await fetch(`/api/clockify/v2/reports?${params}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Impossibile caricare il report"); setReport(data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Errore di caricamento"); } finally { setLoading(false); } }, [params, tab]);
  useEffect(() => { void load(); }, [load]);
  function change(name: string, value: string): void { setFilters((current) => ({ ...current, [name]: value })); }
  async function createShare(): Promise<void> { const response = await fetch("/api/clockify/v2/reports/shares", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== "")), reportType, groupBy: groupBy || undefined, roundingIncrement: increment || undefined, roundingMode: increment ? mode : undefined }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Impossibile creare la condivisione"); return; } setShareUrl(`${window.location.origin}/clockify/shared/${data.token}`); await load(); }
  async function revoke(id: string): Promise<void> { const response = await fetch(`/api/clockify/v2/reports/shares/${id}/revoke`, { method: "POST" }); if (response.ok) await load(); else setError((await response.json()).error || "Impossibile revocare"); }
  async function loadMore(): Promise<void> { if (!report?.nextCursor) return; setLoading(true); try { const response = await fetch(`/api/clockify/v2/reports?${params}&cursor=${encodeURIComponent(report.nextCursor)}&limit=100`, { cache: "no-store" }); const next = await response.json(); if (!response.ok) throw new Error(next.error || "Impossibile caricare la pagina"); setReport((current: any) => ({ ...next, rows: current.type === "detailed" ? [...current.rows, ...next.rows] : current.rows, people: current.type === "weekly" ? [...current.people, ...next.people] : current.people })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Errore di caricamento"); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-secondary"><div className="report-page mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6 sm:py-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Report Clockify</h1><p className="text-sm text-muted-foreground">Dati calcolati sul server, con perimetro aggiornato in tempo reale.</p></div><div className="report-no-print flex gap-2"><Button variant="outline" onClick={() => window.print()}><Printer className="mr-1 h-4 w-4" />Stampa</Button>{tab !== "shared" && <Button asChild variant="outline"><a href={`/api/clockify/v2/reports/export?${params}`}><Download className="mr-1 h-4 w-4" />CSV</a></Button>}</div></div>
    <Tabs value={tab} onValueChange={(value) => setTab(value as typeof tab)}><TabsList aria-label="Tipo di report"><TabsTrigger value="summary">Riepilogo</TabsTrigger><TabsTrigger value="detailed">Dettaglio</TabsTrigger><TabsTrigger value="weekly">Settimanale</TabsTrigger><TabsTrigger value="shared">Condivisi</TabsTrigger></TabsList>
      {tab !== "shared" && <Card className="report-no-print mt-4"><CardContent className="grid gap-3 pt-6 sm:grid-cols-2 lg:grid-cols-4"><Filter label="Da"><Input type="date" value={filters.from} onChange={(event) => change("from", event.target.value)} /></Filter><Filter label="A"><Input type="date" value={filters.to} onChange={(event) => change("to", event.target.value)} /></Filter><Filter label="Descrizione"><Input value={filters.description} onChange={(event) => change("description", event.target.value)} placeholder="Contiene…" /></Filter><Filter label="Cliente"><Input value={filters.client} onChange={(event) => change("client", event.target.value)} /></Filter><Filter label="Reparto"><Input value={filters.department} onChange={(event) => change("department", event.target.value)} /></Filter><Filter label="Utente ID"><Input value={filters.userId} onChange={(event) => change("userId", event.target.value)} /></Filter><Filter label="Progetto ID"><Input value={filters.projectId} onChange={(event) => change("projectId", event.target.value)} /></Filter><Filter label="Task ID"><Input value={filters.taskId} onChange={(event) => change("taskId", event.target.value)} /></Filter><Filter label="Tag"><Input value={filters.tag} onChange={(event) => change("tag", event.target.value)} /></Filter><Filter label="Blocco"><Choice value={filters.locked || "all"} onChange={(value) => change("locked", value === "all" ? "" : value)} options={[["all", "Tutti"], ["true", "Bloccati"], ["false", "Non bloccati"]]} /></Filter><Filter label="Fatturabile"><Choice value={filters.billable || "all"} onChange={(value) => change("billable", value === "all" ? "" : value)} options={[["all", "Tutti"], ["true", "Sì"], ["false", "No"]]} /></Filter><Filter label="Raggruppa"><Choice value={groupBy || "none"} onChange={(value) => setGroupBy(value === "none" ? "" : value)} options={[["none", "Nessuno"], ["client", "Cliente"], ["project", "Progetto"], ["description", "Descrizione"], ["task", "Task"], ["tag", "Tag"], ["user", "Utente"]]} /></Filter><Filter label="Arrotondamento"><Choice value={increment || "none"} onChange={(value) => setIncrement(value === "none" ? "" : value)} options={[["none", "Nessuno"], ["5", "5 min"], ["10", "10 min"], ["15", "15 min"], ["30", "30 min"]]} /></Filter>{increment && <Filter label="Modalità"><Choice value={mode} onChange={setMode} options={[["nearest", "Più vicino"], ["up", "Per eccesso"], ["down", "Per difetto"]]} /></Filter>}<div className="flex items-end gap-2"><Button onClick={() => void load()} disabled={loading}>{loading ? "Caricamento…" : "Aggiorna"}</Button><Button variant="outline" onClick={() => void createShare()}><Share2 className="mr-1 h-4 w-4" />Condividi</Button></div></CardContent></Card>}
      {error && <p role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}
      <TabsContent value="summary"><Summary report={report} /></TabsContent><TabsContent value="detailed"><Detailed report={report} onLoadMore={loadMore} loading={loading} /></TabsContent><TabsContent value="weekly"><Weekly report={report} onLoadMore={loadMore} loading={loading} /></TabsContent><TabsContent value="shared"><Shares shares={shares} shareUrl={shareUrl} onRevoke={revoke} /></TabsContent>
    </Tabs></div></main>;
}
function Filter({ label, children }: { label: string; children: React.ReactNode }): JSX.Element { return <div className="space-y-1"><Label>{label}</Label>{children}</div>; }
function Choice({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: Array<[string, string]> }): JSX.Element { return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{options.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>; }
function Summary({ report }: { report: any }): JSX.Element { if (!report) return <Loading />; return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Totale" value={minutes(report.totalMin || 0)} /><Metric label="Fatturabile" value={minutes(report.billableMin || 0)} /><Metric label="Attività" value={String(report.entryCount || 0)} /></div><div className="grid gap-4 lg:grid-cols-2"><Chart title="Andamento" data={report.timeSeries || []} dataKey="date" /><Chart title="Distribuzione" data={report.bar || []} dataKey="label" /></div></div>; }
function Metric({ label, value }: { label: string; value: string }): JSX.Element { return <Card><CardHeader><CardTitle className="text-sm font-medium text-muted-foreground">{label}</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{value}</CardContent></Card>; }
function Chart({ title, data, dataKey }: { title: string; data: any[]; dataKey: string }): JSX.Element { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey={dataKey} hide={data.length > 12} /><YAxis /><Tooltip /><Legend /><Bar dataKey="totalMin" name="Minuti" fill="#7c3aed" /></BarChart></ResponsiveContainer></CardContent></Card>; }
function Detailed({ report, onLoadMore, loading }: { report: any; onLoadMore: () => Promise<void>; loading: boolean }): JSX.Element { if (!report) return <Loading />; return <Card><CardHeader><CardTitle>Dettaglio · {minutes(report.total?.totalMin || 0)}</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th>Data</th><th>Utente</th><th>Progetto</th><th>Descrizione</th><th>Minuti</th></tr></thead><tbody>{(report.rows || []).map((row: any) => <tr className="border-b" key={row.id}><td>{String(row.workDate).slice(0, 10)}</td><td>{row.userName || row.userEmail}</td><td>{row.client} / {row.projectName}</td><td>{row.description}</td><td>{row.durationMin}</td></tr>)}</tbody></table>{report.nextCursor && <Button className="mt-3" variant="outline" disabled={loading} onClick={() => void onLoadMore()}>{loading ? "Caricamento…" : "Carica altro"}</Button>}</CardContent></Card>; }
function Weekly({ report, onLoadMore, loading }: { report: any; onLoadMore: () => Promise<void>; loading: boolean }): JSX.Element { if (!report) return <Loading />; return <Card><CardHeader><CardTitle>Settimanale · {minutes(report.grandTotalMin || 0)}</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b"><th className="text-left">Persona</th>{(report.days || []).map((day: string) => <th key={day}>{day.slice(5)}</th>)}<th>Totale</th></tr></thead><tbody>{(report.people || []).map((person: any) => <tr className="border-b" key={person.userId}><td className="text-left">{person.name}</td>{person.days.map((day: any) => <td key={day.date}>{day.totalMin}</td>)}<td className="font-medium">{person.totalMin}</td></tr>)}<tr className="font-bold"><td className="text-left">Totale</td>{(report.dayTotals || []).map((day: any) => <td key={day.date}>{day.totalMin}</td>)}<td>{report.grandTotalMin}</td></tr></tbody></table>{report.nextCursor && <Button className="mt-3" variant="outline" disabled={loading} onClick={() => void onLoadMore()}>{loading ? "Caricamento…" : "Carica altro"}</Button>}</CardContent></Card>; }
function Shares({ shares, shareUrl, onRevoke }: { shares: any[]; shareUrl: string; onRevoke: (id: string) => Promise<void> }): JSX.Element { return <Card><CardHeader><CardTitle>Condivisioni pubbliche</CardTitle></CardHeader><CardContent className="space-y-3">{shareUrl && <div className="rounded border p-3 text-sm"><p className="font-medium">Copia ora questo link: non verrà mostrato di nuovo.</p><a className="break-all text-primary underline" href={shareUrl} target="_blank" rel="noreferrer">{shareUrl}</a></div>}<p className="text-sm text-muted-foreground">Le condivisioni sono in sola lettura e restano vincolate al perimetro attuale dell’autore.</p>{shares.map((share) => <div className="flex flex-wrap items-center justify-between gap-2 rounded border p-3" key={share.id}><span className="text-sm">{share.reportType} · {new Date(share.createdAt).toLocaleString("it-IT")} {share.revokedAt ? "· revocata" : ""}</span>{!share.revokedAt && <Button variant="outline" size="sm" onClick={() => void onRevoke(share.id)}>Revoca</Button>}</div>)}{shares.length === 0 && <p className="text-sm text-muted-foreground">Nessuna condivisione.</p>}</CardContent></Card>; }
function Loading(): JSX.Element { return <p className="py-8 text-sm text-muted-foreground">Caricamento report…</p>; }
